[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
sea_escrow = "HqAjfWXQbRto2wtvCCWr1BNiP1WGKW5fazxbuJrswRmo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenchan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
